version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    network_mode: "host"
    env_file:
      - ".env"

  adminer:
    image: adminer
    restart: always
    network_mode: "host"

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always

    env_file:
      - ".env"
